language: node_js
node_js:
  - "6.10.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g preact-cli
  - npm install

script:
  - preact build --prerenderUrls fragments.json

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email:
    on_failure: change
    on_success: change